### ISSUE TITLE
Missing .meta files for DLLs

### ISSUE THREAD

**Issue by PizzaHi5** [Nethereum/Nethereum.Unity#1]
I spoke briefly with @juanfranblanco on discord. When installing the package following the guidance specified, I ran into an error stating that I could not download the package because the repository did not include .meta files. Upon inspecting the repo and doing some research into why I am getting this error, I suspect it has something to do with missing .meta files for .dll for Unity. Juan mentioned that his build auto generated them however that does not occur when downloading the package. I hope adding a .meta file for each .dll will solve the problem! :) Thank you for your help Juan!

**Comment by abuffie** [comment]
With Unity projects, the meta files are auto generated when new files are created however they or not temp files and NEED to be committed with the project.

I also just tried to pull this in via the package manager and Unity ignored all the files do to the missing meta files, the new package management system is less forgiving then just adding files directly to the project which "would recreate the meta files and create issues within a team if using git", if its not 100% set up right, unity will not import the package.

**Comment by abuffie** [comment]
This issue is resolved, just pulled in the latest and see the meta files have been added and all is working.
Thanks @juanfranblanco
