### ISSUE TITLE
Is it compatible with unity 2020.3.23f1? Is any special version of unity recommended?

### ISSUE THREAD

**Issue by Vlakdo** [Nethereum/Nethereum.Unity#3]
Thank you, the doubt is the one I specified in the title.

**Comment by juanfranblanco** [comment]
@Vlakdo Depends what you target, it you are targeting anything but WebGl you should be ok. If you are planning to use Wegl 2021 and above is required due to emscripten changes.

**Comment by AArtlone** [comment]
@juanfranblanco 
Hi!
Is there anything special that I need to do to make it work in WebGL?
I got a setup that is working in Unity, but it does not work in WebGL. I am currently debugging to see what's going wrong.
I am using Unity 2022.3.19

**Comment by juanfranblanco** [comment]
If you are using async you will need to use the Webgl thread patcher.  See the notes here: https://github.com/Nethereum/Unity3dSampleTemplate
