### ISSUE TITLE
Please set up Assembly Definitions

### ISSUE THREAD

**Issue by AArtlone** [Nethereum/Nethereum.Unity#4]
It is problematic for projects that use Assembly Definitions to reference scripts from your plugin.

**Comment by AArtlone** [comment]
https://docs.unity3d.com/Manual/CustomPackages.html
It is one of the first things Unity tell you to do when creating a package.
I am still trying to find a solution and I am not succeeding, I might need to completely remove Assembly Definitions from my project...

**Comment by AArtlone** [comment]
Update:
somehow after the 3 reimport of the plugin it worked. Now out of nowhere my scripts inside assembly definitions are able to access Nethereum scripts.

**Comment by skibitsky** [comment]
I can confirm that Nethereum.Unity can't be referenced when installed with git url or from OpenUPM. Tested with Unity 2022.3.18.
